apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-gl-onprem-l5x1rqa3pwr4l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-gl-onprem-l5x1rqa3pwr4l
    app.kubernetes.io/part-of: application-gl-onprem-3tuumwxj13a4i
  name: component-gl-onprem-l5x1rqa3pwr4l
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-gl-onprem-l5x1rqa3pwr4l
status:
  loadBalancer: {}
